---
pipeline:

  pull:
    when:
      event: push
    image: docker
    volumes:
      - /secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker --config /secrets/ pull 1and1internet/template-library-tools
      - docker --config /secrets/ pull 1and1internet/ubuntu-16-rspec

  build:
    when:
      event: push
    image: 1and1internet/template-library-tools
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make --environment-overrides build IMAGE_NAME=build-${CI_REPO#*/}-${CI_BUILD_NUMBER}/${CI_REPO#*/}

  test:
    when:
      event: push
    image: 1and1internet/ubuntu-16-rspec
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make --environment-overrides do-test IMAGE_NAME=build-${CI_REPO#*/}-${CI_BUILD_NUMBER}/${CI_REPO#*/}

  publish:
    when:
      event: push
    image: 1and1internet/template-library-tools
    volumes:
      - /secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
      - /shared_storage:/tmp/image-comparison
    commands:
      - python3 -u /scripts/images/publish.py

  clean:
    when:
      event: push
      status: [success, failure]
    image: 1and1internet/template-library-tools
    volumes:
      - /secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make --environment-overrides clean IMAGE_NAME=build-${CI_REPO#*/}-${CI_BUILD_NUMBER}/${CI_REPO#*/}
